<?php

use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [
            'AFN' => 'Afghan Afghani',
            'ALL' => 'Albanian Lek',
            'DZD' => 'Algerian Dinar',
            'ADP' => 'Andorran Peseta',
            'AOA' => 'Angolan Kwanza',
            'ARA' => 'Argentine Austral',
            'ARS' => 'Argentine Peso',
            'AMD' => 'Armenian Dram',
            'AWG' => 'Aruban Florin',
            'AUD' => 'Australian Dollar',
            'ATS' => 'Austrian Schilling',
            'AZN' => 'Azerbaijani Manat',
            'BSD' => 'Bahamian Dollar',
            'BHD' => 'Bahraini Dinar',
            'BDT' => 'Bangladeshi Taka',
            'BBD' => 'Barbadian Dollar',
            'BYR' => 'Belarusian Ruble',
            'BEF' => 'Belgian Franc',
            'BZD' => 'Belize Dollar',
            'BMD' => 'Bermudan Dollar',
            'BTN' => 'Bhutanese Ngultrum',
            'BOB' => 'Bolivian Boliviano',
            'BOV' => 'Bolivian Mvdol',
            'BOP' => 'Bolivian Peso',
            'BAM' => 'Bosnia-Herzegovina Convertible Mark',
            'BWP' => 'Botswanan Pula',
            'BRL' => 'Brazilian Real',
            'GBP' => 'British Pound Sterling',
            'BND' => 'Brunei Dollar',
            'BGL' => 'Bulgarian Hard Lev',
            'BGN' => 'Bulgarian Lev',
            'BGM' => 'Bulgarian Socialist Lev',
            'BUK' => 'Burmese Kyat',
            'BIF' => 'Burundian Franc',
            'KHR' => 'Cambodian Riel',
            'CAD' => 'Canadian Dollar',
            'CVE' => 'Cape Verdean Escudo',
            'KYD' => 'Cayman Islands Dollar',
            'XOF' => 'CFA Franc BCEAO',
            'XAF' => 'CFA Franc BEAC',
            'XPF' => 'CFP Franc',
            'CLE' => 'Chilean Escudo',
            'CLP' => 'Chilean Peso',
            'CNX' => 'Chinese People’s Bank Dollar',
            'CNY' => 'Chinese Yuan',
            'COP' => 'Colombian Peso',
            'COU' => 'Colombian Real Value Unit',
            'KMF' => 'Comorian Franc',
            'CDF' => 'Congolese Franc',
            'CRC' => 'Costa Rican Colón',
            'HRD' => 'Croatian Dinar',
            'HRK' => 'Croatian Kuna',
            'CUC' => 'Cuban Convertible Peso',
            'CUP' => 'Cuban Peso',
            'CYP' => 'Cypriot Pound',
            'CZK' => 'Czech Republic Koruna',
            'CSK' => 'Czechoslovak Hard Koruna',
            'DKK' => 'Danish Krone',
            'DJF' => 'Djiboutian Franc',
            'DOP' => 'Dominican Peso',
            'NLG' => 'Dutch Guilder',
            'XCD' => 'East Caribbean Dollar',
            'DDM' => 'East German Mark',
            'ECS' => 'Ecuadorian Sucre',
            'ECV' => 'Ecuadorian Unit of Constant Value',
            'EGP' => 'Egyptian Pound',
            'GQE' => 'Equatorial Guinean Ekwele',
            'ERN' => 'Eritrean Nakfa',
            'EEK' => 'Estonian Kroon',
            'ETB' => 'Ethiopian Birr',
            'EUR' => 'Euro',
            'XEU' => 'European Currency Unit',
            'FKP' => 'Falkland Islands Pound',
            'FJD' => 'Fijian Dollar',
            'FIM' => 'Finnish Markka',
            'FRF' => 'French Franc',
            'XFO' => 'French Gold Franc',
            'XFU' => 'French UIC-Franc',
            'GMD' => 'Gambian Dalasi',
            'GEK' => 'Georgian Kupon Larit',
            'GEL' => 'Georgian Lari',
            'DEM' => 'German Mark',
            'GHS' => 'Ghanaian Cedi',
            'GIP' => 'Gibraltar Pound',
            'GRD' => 'Greek Drachma',
            'GTQ' => 'Guatemalan Quetzal',
            'GWP' => 'Guinea-Bissau Peso',
            'GNF' => 'Guinean Franc',
            'GNS' => 'Guinean Syli',
            'GYD' => 'Guyanaese Dollar',
            'HTG' => 'Haitian Gourde',
            'HNL' => 'Honduran Lempira',
            'HKD' => 'Hong Kong Dollar',
            'HUF' => 'Hungarian Forint',
            'ISK' => 'Icelandic Króna',
            'INR' => 'Indian Rupee',
            'IDR' => 'Indonesian Rupiah',
            'IRR' => 'Iranian Rial',
            'IQD' => 'Iraqi Dinar',
            'IEP' => 'Irish Pound',
            'ILS' => 'Israeli New Sheqel',
            'ILP' => 'Israeli Pound',
            'ITL' => 'Italian Lira',
            'JMD' => 'Jamaican Dollar',
            'JPY' => 'Japanese Yen',
            'JOD' => 'Jordanian Dinar',
            'KZT' => 'Kazakhstani Tenge',
            'KES' => 'Kenyan Shilling',
            'KWD' => 'Kuwaiti Dinar',
            'KGS' => 'Kyrgystani Som',
            'LAK' => 'Laotian Kip',
            'LVL' => 'Latvian Lats',
            'LVR' => 'Latvian Ruble',
            'LBP' => 'Lebanese Pound',
            'LSL' => 'Lesotho Loti',
            'LRD' => 'Liberian Dollar',
            'LYD' => 'Libyan Dinar',
            'LTL' => 'Lithuanian Litas',
            'LTT' => 'Lithuanian Talonas',
            'LUL' => 'Luxembourg Financial Franc',
            'LUC' => 'Luxembourgian Convertible Franc',
            'LUF' => 'Luxembourgian Franc',
            'MOP' => 'Macanese Pataca',
            'MKD' => 'Macedonian Denar',
            'MGA' => 'Malagasy Ariary',
            'MGF' => 'Malagasy Franc',
            'MWK' => 'Malawian Kwacha',
            'MYR' => 'Malaysian Ringgit',
            'MVR' => 'Maldivian Rufiyaa',
            'MLF' => 'Malian Franc',
            'MTL' => 'Maltese Lira',
            'MTP' => 'Maltese Pound',
            'MRO' => 'Mauritanian Ouguiya',
            'MUR' => 'Mauritian Rupee',
            'MXV' => 'Mexican Investment Unit',
            'MXN' => 'Mexican Peso',
            'MDC' => 'Moldovan Cupon',
            'MDL' => 'Moldovan Leu',
            'MCF' => 'Monegasque Franc',
            'MNT' => 'Mongolian Tugrik',
            'MAD' => 'Moroccan Dirham',
            'MAF' => 'Moroccan Franc',
            'MZE' => 'Mozambican Escudo',
            'MZN' => 'Mozambican Metical',
            'MMK' => 'Myanmar Kyat',
            'NAD' => 'Namibian Dollar',
            'NPR' => 'Nepalese Rupee',
            'ANG' => 'Netherlands Antillean Guilder',
            'TWD' => 'New Taiwan Dollar',
            'NZD' => 'New Zealand Dollar',
            'NIO' => 'Nicaraguan Córdoba',
            'NGN' => 'Nigerian Naira',
            'KPW' => 'North Korean Won',
            'NOK' => 'Norwegian Krone',
            'OMR' => 'Omani Rial',
            'PKR' => 'Pakistani Rupee',
            'PAB' => 'Panamanian Balboa',
            'PGK' => 'Papua New Guinean Kina',
            'PYG' => 'Paraguayan Guarani',
            'PEI' => 'Peruvian Inti',
            'PEN' => 'Peruvian Nuevo Sol',
            'PHP' => 'Philippine Peso',
            'PLN' => 'Polish Zloty',
            'PTE' => 'Portuguese Escudo',
            'GWE' => 'Portuguese Guinea Escudo',
            'QAR' => 'Qatari Rial',
            'RHD' => 'Rhodesian Dollar',
            'XRE' => 'RINET Funds',
            'RON' => 'Romanian Leu',
            'RUB' => 'Russian Ruble',
            'RWF' => 'Rwandan Franc',
            'SVC' => 'Salvadoran Colón',
            'WST' => 'Samoan Tala',
            'STD' => 'São Tomé & Príncipe Dobra',
            'SAR' => 'Saudi Riyal',
            'RSD' => 'Serbian Dinar',
            'SCR' => 'Seychellois Rupee',
            'SLL' => 'Sierra Leonean Leone',
            'SGD' => 'Singapore Dollar',
            'SKK' => 'Slovak Koruna',
            'SIT' => 'Slovenian Tolar',
            'SBD' => 'Solomon Islands Dollar',
            'SOS' => 'Somali Shilling',
            'ZAR' => 'South African Rand',
            'KRW' => 'South Korean Won',
            'SSP' => 'South Sudanese Pound',
            'SUR' => 'Soviet Rouble',
            'ESP' => 'Spanish Peseta',
            'LKR' => 'Sri Lankan Rupee',
            'SHP' => 'St. Helena Pound',
            'SDG' => 'Sudanese Pound',
            'SRD' => 'Surinamese Dollar',
            'SRG' => 'Surinamese Guilder',
            'SZL' => 'Swazi Lilangeni',
            'SEK' => 'Swedish Krona',
            'CHF' => 'Swiss Franc',
            'SYP' => 'Syrian Pound',
            'TJR' => 'Tajikistani Ruble',
            'TJS' => 'Tajikistani Somoni',
            'TZS' => 'Tanzanian Shilling',
            'THB' => 'Thai Baht',
            'TPE' => 'Timorese Escudo',
            'TOP' => 'Tongan Paʻanga',
            'TTD' => 'Trinidad & Tobago Dollar',
            'TND' => 'Tunisian Dinar',
            'TRY' => 'Turkish Lira',
            'TMT' => 'Turkmenistani Manat',
            'UGX' => 'Ugandan Shilling',
            'UAH' => 'Ukrainian Hryvnia',
            'UAK' => 'Ukrainian Karbovanets',
            'AED' => 'United Arab Emirates Dirham',
            'UYU' => 'Uruguayan Peso',
            'USD' => 'US Dollar',
            'UZS' => 'Uzbekistan Som',
            'VUV' => 'Vanuatu Vatu',
            'VEF' => 'Venezuelan Bolívar',
            'VND' => 'Vietnamese Dong',
            'CHE' => 'WIR Euro',
            'CHW' => 'WIR Franc',
            'YDD' => 'Yemeni Dinar',
            'YER' => 'Yemeni Rial',
            'ZMW' => 'Zambian Kwacha',
        ];

        $data = [];
        foreach ($currencies as $key => $name){
            array_push($data, [
                'code' => $key,
                'name' => $name,
                'available' => true
            ]);
        }

        \App\Currency::unguard();

        \App\Currency::insert($data);

        \App\Currency::reguard();

    }
}
